backup

diff --git a/cdist/conf/type/__update_alternatives/explorer/link b/cdist/conf/type/__update_alternatives/explorer/link
--- a/cdist/conf/type/__update_alternatives/explorer/link
+++ b/cdist/conf/type/__update_alternatives/explorer/link
@@ -18,23 +18,19 @@ for altdir in \
     /var/lib/dpkg/alternatives \
     /var/lib/alternatives
 do
-    if [ ! -f "$altdir/$__object_id" ]
-    then
-        continue
-    fi
+    test -f "${altdir}/${__object_id:?}" || continue
 
-    link="$( awk 'NR==2' "$altdir/$__object_id" )"
+    link=$(awk 'NR==2' "${altdir}/${__object_id:?}")
 
-    if [ -n "$link" ]
+    if test -n "${link}"
     then
         break
     fi
 done
 
-if [ -z "$link" ]
-then
-    echo "unable to get link for $__object_id" >&2
+test -n "${link}" || {
+    echo "unable to get link for ${__object_id:?}" >&2
     exit 1
-fi
+}
 
 echo "$link"
diff --git a/cdist/conf/type/__update_alternatives/explorer/path_is b/cdist/conf/type/__update_alternatives/explorer/path_is
--- a/cdist/conf/type/__update_alternatives/explorer/path_is
+++ b/cdist/conf/type/__update_alternatives/explorer/path_is
@@ -1,12 +1,12 @@
 #!/bin/sh -e
 
-path_is="$( update-alternatives --display "$__object_id" 2>/dev/null \
-    | awk '/link currently points to/ {print $5}' )"
+path_is=$(LC_ALL=C update-alternatives --display "${__object_id?}" 2>/dev/null \
+    | awk '/link currently points to/ { print $5 }')
 
-if [ -z "$path_is" ]
+if test -n "${path_is}"
 then
-    echo "unable to get current path for $__object_id" >&2
+    echo "${path_is}"
+else
+    echo "unable to get current path for ${__object_id:?}" >&2
     exit 1
 fi
-
-echo "$path_is"
